from exc._base import BaseException


class DbException(BaseException):
    pass
